Update GH workflow and minor security update for building container

diff --git a/.github/workflows/publish-crossbuild.yml b/.github/workflows/publish-crossbuild.yml
--- a/.github/workflows/publish-crossbuild.yml
+++ b/.github/workflows/publish-crossbuild.yml
@@ -4,22 +4,45 @@ on:
   push:
     branches:
       - main
-    #paths:
-    #  - 'release-versions/*'
+    # paths:
+    # - 'release-versions/*'
+env:
+  CONTAINER_REGISTRY_BASE_URI: registry.gitlab.com/patrickdung/wikijs
 
 jobs:
-  build-docker-images:
+  build-docker-image:
     name: Build Docker Images
     runs-on: ubuntu-latest
     continue-on-error: true
-
+    permissions:
+      actions: none
+      checks: none
+      contents: read
+      deployments: none
+      issues: none
+      packages: write
+      pull-requests: none
+      repository-projects: none
+      security-events: none
+      statuses: none
+      # id-token: 'read'
+    outputs:
+      remote_branch_name: ${{ steps.get-remote-branch-name.outputs.remote_branch_name }}
+      container_registry_base_uri: ${{ steps.set-env.outputs.container_registry_base_uri }}
+      container_digest_amd64: ${{ steps.get-container-digest-amd64.outputs.container_digest }}
+      container_digest_arm64: ${{ steps.get-container-digest-arm64.outputs.container_digest }}
     steps:
-
-      - name: Fetch branch name of latest release
+      - name: Set env for later jobs
+        id: set-env
+        run: |
+          echo "::set-output name=container_registry_base_uri::$(echo $CONTAINER_REGISTRY_BASE_URI)"
+      - name: Get branch name of latest release from official repo
+        id: get-remote-branch-name
         run: |
           curl -sL https://api.github.com/repos/Requarks/wiki/releases/latest | \
           jq -r ".tag_name" > /tmp/wikijs-latest-branch-name
           echo "REMOTE_BRANCH_NAME=$(cat /tmp/wikijs-latest-branch-name)" >> $GITHUB_ENV
+          echo "::set-output name=remote_branch_name::$(cat /tmp/goatcounter-latest-branch-name)"
 
       #- name: Fetch commit digest of latest release
       #  run: |
@@ -48,8 +71,8 @@ jobs:
       - name: Local pre-build update/fixes
         working-directory: ./wiki
         run: |
-           #pwd
-           #ls -lR .
+           # pwd
+           # ls -lR .
            ls -lR ..
            cp -p package.json package.json.orig
            mv package.json pkg-temp.json
@@ -58,6 +81,34 @@ jobs:
            cat package.json
            yarn upgrade apollo-server@2.25.3 apollo-server-express@2.25.3 json-schema@0.4.0 nth-check@2.0.1 highlight.js@10.7.3 node-uuid@1.4.8 ansi-regex@5.0.1 ws@7.4.6
            if [ -e yarn-error.log ]; then cat yarn-error.log; fi
+
+      - name: Remove uncessary files
+        working-directoy: ./wiki
+        run: |
+          set -eux && \
+          rm -f -v \
+            ./node_modules/connect-session-knex/node_modules/knex/scripts/docker-compose.yml \
+            ./node_modules/connect-session-knex/node_modules/knex/scripts/stress-test/docker-compose.yml \
+            ./node_modules/cpu-features/deps/cpu_features/.github/workflows/Dockerfile \
+            ./node_modules/getos/Dockerfile \
+            ./node_modules/getos/tests/alpine/3.3/Dockerfile \
+            ./node_modules/getos/tests/debian/7.3/Dockerfile \
+            ./node_modules/getos/tests/debian/7.4/Dockerfile \
+            ./node_modules/getos/tests/debian/7.5/Dockerfile \
+            ./node_modules/getos/tests/debian/7.6/Dockerfile \
+            ./node_modules/getos/tests/fedora/20/Dockerfile \
+            ./node_modules/getos/tests/ubuntu/13.10/Dockerfile \
+            ./node_modules/getos/tests/ubuntu/14.04/Dockerfile \
+            ./node_modules/knex/scripts/docker-compose.yml \
+            ./node_modules/knex/scripts/stress-test/docker-compose.yml \
+            ./node_modules/sqlite3/Dockerfile \
+            ./node_modules/sqlite3/tools/docker/architecture/linux-arm64/Dockerfile \
+            ./node_modules/sqlite3/tools/docker/architecture/linux-arm/Dockerfile \
+            ./node_modules/ssh2-promise/pretest/docker-compose.yml \
+            ./node_modules/ssh2-promise/pretest/ssh/Dockerfile \
+            ./node_modules/ssh2/test/fixtures/id_dsa \
+            ./node_modules/ssh2/test/fixtures/id_ecdsa \
+            ./node_modules/ssh2/test/fixtures/id_rsa
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
@@ -72,6 +123,11 @@ jobs:
           username: ${{ secrets.GITLAB_USERNAME }}
           password: ${{ secrets.GITLAB_TOKEN }}
 
+      - name: Install Cosign GH action
+        uses: sigstore/cosign-installer@main
+        # with:
+        #  cosign-release: 'v1.4.1'
+
       - name: Build and push to container registry
         uses: docker/build-push-action@v2
         # ./Dockerfile is in the upper directory
@@ -83,4 +139,210 @@ jobs:
           ##  ARCH=${{ env.TO_BE_FIXED }}
           platforms: linux/amd64,linux/arm64
           push: true
-          tags: registry.gitlab.com/patrickdung/wikijs:${{ env.REMOTE_BRANCH_NAME }}
+          # registry.gitlab.com/patrickdung/wikijs:${{ env.REMOTE_BRANCH_NAME }}
+          tags: |
+            ${{env.CONTAINER_REGISTRY_BASE_URI}}:${{ env.REMOTE_BRANCH_NAME }}
+
+      - name: "Get the digest of container (amd64)"
+        id: get-container-digest-amd64
+        run: |
+          skopeo inspect --raw docker://${{env.CONTAINER_REGISTRY_BASE_URI}}:${{env.REMOTE_BRANCH_NAME}} | \
+            jq -r '.manifests[] | select(.platform .architecture=="amd64" and .platform .os=="linux") | .digest' > /tmp/container-digest-amd64
+          echo "::set-output name=container_digest::$(cat /tmp/container-digest-amd64)"
+
+      - name: "Get the digest of container (arm64)"
+        id: get-container-digest-arm64
+        run: |
+          skopeo inspect --raw docker://${{env.CONTAINER_REGISTRY_BASE_URI}}:${{env.REMOTE_BRANCH_NAME}} | \
+            jq -r '.manifests[] | select(.platform .architecture=="arm64" and .platform .os=="linux") | .digest' > /tmp/container-digest-arm64
+          echo "::set-output name=container_digest::$(cat /tmp/container-digest-arm64)"
+
+      - name: Use Cosign to sign the image recursively
+        env:
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}
+        run: |
+          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
+          # Sign the multiarch images, the signature is also pushed to the registry
+          cosign sign --recursive --key ./cosign.key "${{env.CONTAINER_REGISTRY_BASE_URI}}:${{ env.REMOTE_BRANCH_NAME }}"
+
+  build-sbom-and-scanning:
+    needs: [build-docker-image]
+    name: Build SBOM and image scanning
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    permissions:
+      actions: none
+      checks: none
+      contents: read
+      deployments: none
+      issues: none
+      packages: write
+      pull-requests: none
+      repository-projects: none
+      # GH action/scanners for sarif reports
+      security-events: write
+      statuses: none
+      # id-token: 'read'
+      # id-token: write # needed for signing the images with GitHub OIDC **not production ready**
+    strategy:
+      # Anchore action produce the same filename for sarif on different platform
+      max-parallel: 1
+      fail-fast: false
+      matrix:
+        include:
+          - arch: amd64
+            platform_image_uri: "${{needs.build-docker-image.outputs.gitlab_container_base_uri}}@${{ needs.build-docker-image.outputs.container_digest_amd64 }}"
+          - arch: arm64
+            platform_image_uri: "${{needs.build-docker-image.outputs.gitlab_container_base_uri}}@${{ needs.build-docker-image.outputs.container_digest_arm64 }}"
+    steps:
+
+      - name: Set env REMOTE_BRANCH_NAME
+        run: |
+          echo "REMOTE_BRANCH_NAME=${{ needs.build-docker-image.outputs.remote_branch_name }}" >> $GITHUB_ENV
+
+      - name: Login to Registry provider
+        uses: docker/login-action@v1
+        with:
+          registry: registry.gitlab.com
+          username: ${{ secrets.GITLAB_USERNAME }}
+          password: ${{ secrets.GITLAB_TOKEN }}
+
+      - name: Install Cosign GH action
+        uses: sigstore/cosign-installer@main
+        # with:
+        #  cosign-release: 'v1.4.1'
+
+      - name: "Fetch branch name of latest release versions Other software"
+        run: |
+          curl -sL https://api.github.com/repos/anchore/syft/releases | \
+            jq -r ".[].tag_name" | grep -v rc | sort -nr -t. -k 1 -k 2 -k 3 | head -n 1 | sed -E 's|^v||' > /tmp/syft-latest-branch-name
+          echo "SYFT_VERSION=$(cat /tmp/syft-latest-branch-name)" >> $GITHUB_ENV
+          curl -sL https://api.github.com/repos/anchore/grype/releases | \
+            jq -r ".[].tag_name" | grep -v rc | sort -nr -t. -k 1 -k 2 -k 3 | head -n 1 | sed -E 's|^v||' > /tmp/grype-latest-branch-name
+          echo "GRYPE_VERSION=$(cat /tmp/grype-latest-branch-name)" >> $GITHUB_ENV
+
+      - name: Install Syft
+        run: |
+          cd /tmp
+          curl -L -O -v https://github.com/anchore/syft/releases/download/v${{env.SYFT_VERSION}}/syft_${{env.SYFT_VERSION}}_linux_amd64.deb
+          curl -L -O -v https://github.com/anchore/syft/releases/download/v${{env.SYFT_VERSION}}/syft_${{env.SYFT_VERSION}}_checksums.txt
+          sha256sum -c syft_${{env.SYFT_VERSION}}_checksums.txt --ignore-missing
+          sudo dpkg -i syft_${{env.SYFT_VERSION}}_linux_amd64.deb
+
+      - name: Set the SBOM env variable for use by later steps
+        run: |
+          echo "ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT=container-sbom.json" >> $GITHUB_ENV
+
+      - name: Use Syft to generate the SBOM files
+        run: |
+          syft -v ${{matrix.platform_image_uri}} -o json > ./${{matrix.arch}}-${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}
+
+      - name: Upload SBOM files to release
+        uses: svenstaro/upload-release-action@v2
+        with:
+          repo_token: ${{ secrets.PUBLISH_TOKEN }}
+          file: ./*${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}
+          file_glob: true
+          tag: ${{ env.REMOTE_BRANCH_NAME }}
+          overwrite: true
+
+      # Cannot download if it's not generated as artifact
+      # - name: Download the container SBOM artifact
+      #  uses: actions/download-artifact@v2
+      #  with:
+      #    #name: container-sbom.spdx.json
+      #    name: ${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}
+
+      - name: Create SBOM attestation
+        env:
+          COSIGN_PASSWORD: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}
+          # ##SBOM_FILE: ./container-sbom.spdx.json
+          # ##SBOM_FILE: ${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}
+        run: |
+          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
+          # CONTAINER_IMAGE=${{matrix.platform_image_uri}}
+          # Create SBOM attestation and push it to the container registry
+          # ##cosign attest --predicate "$SBOM_FILE" --key ./cosign.key "$CONTAINER_IMAGE"
+          cosign attest --predicate "${{matrix.arch}}-${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}}" --key ./cosign.key "${{matrix.platform_image_uri}}"
+
+      - name: Install Grype
+        run: |
+          cd /tmp
+          curl -L -O -v https://github.com/anchore/grype/releases/download/v${{env.GRYPE_VERSION}}/grype_${{env.GRYPE_VERSION}}_linux_amd64.deb
+          curl -L -O -v https://github.com/anchore/grype/releases/download/v${{env.GRYPE_VERSION}}/grype_${{env.GRYPE_VERSION}}_checksums.txt
+          sha256sum -c grype_${{env.GRYPE_VERSION}}_checksums.txt --ignore-missing
+          sudo dpkg -i grype_${{env.GRYPE_VERSION}}_linux_amd64.deb
+
+      - name: Scan container by Grype
+        run: |
+          # May set a severity threshold for failing the build
+          grype sbom:./${{matrix.arch}}-${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}} -o json > ./${{matrix.arch}}-container-vulnerabilities-report-grype.json
+          grype sbom:./${{matrix.arch}}-${{env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT}} -o table > ./${{matrix.arch}}-container-vulnerabilities-report-grype-table.txt
+
+      - name: Upload Grype reports to artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          path: ./*vulnerabilities-report-grype*
+          name: "Vulnerabilities reports by Grype"
+
+      - name: Upload Grype reports to release
+        uses: svenstaro/upload-release-action@v2
+        with:
+          repo_token: ${{ secrets.PUBLISH_TOKEN }}
+          file: ./*vulnerabilities-report-grype*
+          file_glob: true
+          tag: ${{ env.REMOTE_BRANCH_NAME }}
+          overwrite: true
+
+      - name: Scan container with Trivy
+        uses: aquasecurity/trivy-action@master
+        id: scan-by-trivy
+        with:
+          image-ref: '${{matrix.platform_image_uri}}'
+          format: 'template'
+          template: '@/contrib/sarif.tpl'
+          output: '${{matrix.arch}}-container-trivy-results.sarif'
+          severity: 'CRITICAL,HIGH'
+
+      - name: Upload Trivy SARIF report to GitHub Security tab
+        uses: github/codeql-action/upload-sarif@v1
+        with:
+          sarif_file: '${{matrix.arch}}-container-trivy-results.sarif'
+          category: trivy-${{matrix.arch}}
+
+      - name: Scan container by Anchore
+        uses: anchore/scan-action@v3
+        # ## id: scan-by-anchore-${{matrix.arch}}
+        id: scan-by-anchore
+        with:
+          fail-build: false
+          image: "${{matrix.platform_image_uri}}"
+          acs-report-enable: true
+
+      - name: Rename results.sarif with architecture name
+        run: |
+          mv results.sarif ${{matrix.arch}}-container-anchore-results.sarif
+
+      - name: Upload Anchore SARIF report to GitHub Security tab
+        uses: github/codeql-action/upload-sarif@v1
+        with:
+          # the steps outputs would contain './'
+          # ##sarif_file: ${{matrix.arch}}-${{ steps.scan-by-anchore-${{matrix.arch}}.outputs.sarif }}
+          # sarif_file: anchore-${{matrix.arch}}-${{ steps.scan-by-anchore.outputs.sarif }}
+          sarif_file: ./${{matrix.arch}}-container-anchore-results.sarif
+          category: anchore-${{matrix.arch}}
+
+      - name: Inspect SARIF report(s)
+        run: |
+          echo ${{matrix.arch}}
+          cat ${{matrix.arch}}-container-trivy-results.sarif
+          cat ${{matrix.arch}}-container-anchore-results.sarif
+
+      - name: Upload SARIF reports to artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: "SARIF reports when containers are built"
+          path: |
+            # #${{matrix.arch}}-trivy-results.sarif
+            # #${{ steps.scan-by-anchore.outputs.sarif }}
+            ./*.sarif
